name: Terraform destroy

on:
  workflow_dispatch:

env:
  TF_VERSION: 1.0.5
  environment: dev

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: checkout the repo and building the Backend
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.TERRAFORM_DEPLOY_ROLE_ARN }}
          aws-region: ca-central-1

      - name: destroying the  back-end using terraform
        run: |
          cd server
          cat <<EOF > backend.hcl
          bucket = "${{ vars.S3_BACKEND_NAME }}"
          key = "${{ vars.LICENSEPLATE }}/${{ env.environment }}/serverless-app-backend.tfstate"
          dynamodb_table = "${{ vars.DYNAMO_DB_TABLE_NAME }}"
          EOF
          terraform init -backend-config=backend.hcl
          terraform destroy -auto-approve

      - name: destroying front-end
        run: |
          cd client
          cat <<EOF > backend.hcl
          bucket = "${{ vars.S3_BACKEND_NAME }}"
          key = "${{ vars.LICENSEPLATE }}/${{ env.environment }}/serverless-app-frontend.tfstate"
          dynamodb_table = "${{ vars.DYNAMO_DB_TABLE_NAME }}"
          EOF
          terraform init -backend-config=backend.hcl
          terraform destroy -auto-approve
